#!/usr/bin/env python3.6

import os
import math

digits = int(os.getenv('DIGITS') or 10)
print("%.*f" % (digits, math.pi))

# OR

from os import getenv
from math import pi

digits = int(getenv('DIGITS') or 10)

print("%.*f" % (digits, pi))
