#!/usr/bin/env python3

user = { 'admin': True, 'active': True, 'name': 'Kevin' }
prefix = ""

if user["admin"] and user["active"]:
  prefix =  "Active Admin "
elif user["admin"]:
  prefix - "Admin "
elif user["active"]:
  prefix = "Active "

print(prefix + user["name"])
