#!/usr/bin/env python3

users = [
  { 'admin': True, 'active': True, 'name': 'Claudio' },
  { 'admin': True, 'active': False, 'name': 'Alessandro' },
  { 'admin': False, 'active': True, 'name': 'Alberto' },
  { 'admin': False, 'active': False, 'name': 'Daniele' },
]

line = 1

for user in users:
  prefix = f"{line} "

  if user['admin'] and user['active']:
    prefix += "Active Admin "
  elif user['admin']:
    prefix += "Admin "
  elif user['active']:
    prefix += "Active "
  
  print(prefix + user['name'])
  line += 1
