#!/usr/bin/env python3

first_name = "Claudio"
last_name = "A"
age = 30
birth_date = "26-09-1989"

print(f"My name is {first_name} {last_name}." )
print(f"I was born on {birth_date}, and I'm {age} years old.")
